### ISSUE TITLE
上传对象时设置Content-Length无效

### ISSUE THREAD

**Issue by lyd600lty** [yunify/qingstor-sdk-js#28]
https://github.com/yunify/qingstor-sdk-js/blob/master/src/build.js#L76

没有使用传入的Content-Length，并且计算的长度在有中文的时候也不对，
用`Buffer.byteLength`取长度才对吧。。。。。。

**Comment by Xuanwo** [comment]
感谢您的反馈，这确实是实现上的一个 BUG，我们会予以修复。

**Comment by lyd600lty** [comment]
能merge了么。。

**Comment by lyd600lty** [comment]
不测试就关了么？根本就不对。。
